export const EMPLOYEES_LOADED = 'Employees/EMPLOYEES_LOADED';

export const EMPLOYEE_ADDED = 'Employees/EMPLOYEE_ADDED';

export const LAUNCH_DATA_FETCHING = 'Employees/LAUNCH_DATA_FETCHING';
export const DATA_FETCHED_PROPERLY = 'Employees/DATA_FETCHED_PROPERLY';
export const DATA_FETCHING_ERROR = 'Employees/DATA_FETCHING_ERROR';

export const LOGGED_IN_USER = "Users/LOGGED_IN_USER"